// This file will be auto-generated by Supabase CLI
// For now, we'll define basic types based on your Firestore structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          username: string | null
          email: string | null
          created_at: string
          total_study_time: number
          companion_clicks: number
        }
        Insert: {
          id: string
          username?: string | null
          email?: string | null
          created_at?: string
          total_study_time?: number
          companion_clicks?: number
        }
        Update: {
          id?: string
          username?: string | null
          email?: string | null
          created_at?: string
          total_study_time?: number
          companion_clicks?: number
        }
      }
      study_sessions: {
        Row: {
          id: string
          user_id: string
          subject_id: string
          start_time: string
          end_time: string
          duration: number // in minutes
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          subject_id: string
          start_time: string
          end_time: string
          duration: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subject_id?: string
          start_time?: string
          end_time?: string
          duration?: number
          created_at?: string
        }
      }
      subjects: {
        Row: {
          id: string
          user_id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          created_at?: string
        }
      }
      flowers: {
        Row: {
          id: string
          user_id: string
          subject: string
          flower_type_id: string
          grown_at: string
        }
        Insert: {
          id?: string
          user_id: string
          subject: string
          flower_type_id: string
          grown_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subject?: string
          flower_type_id?: string
          grown_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
